name: build_on_push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  firmware:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Fetch submodules
        run: |
          git submodule update --init
          git -C lib/pico-sdk submodule update --init

      - name: Build each example on every commit
        run: |
          mkdir -p examples/build
          cd examples/build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} ..
          make
